In [78]:
import numpy as np
x=np.array([1,3,4,5])
print(x)

print(x.ndim)
print(x.dtype)
print(type(x))

[1 3 4 5]
1
int32
<class 'numpy.ndarray'>


In [25]:
y = np.array([[1,2,5],[1,2,3]])
print(y)
print(y.ndim)
print()

y1 = np.array([[[1,2,5],[5,7,9],[1,2,3]]])
print(y1)
print(y1.ndim)
print()

z=np.array([1,2,3],ndmin=5)
print(z)

[[1 2 5]
 [1 2 3]]
2

[[[1 2 5]
  [5 7 9]
  [1 2 3]]]
3

[[[[[1 2 3]]]]]


In [81]:
import numpy as np
ar_zero=np.zeros((4,5))       #4rows*columns
print(ar_zero)
print()

ar_1=np.ones(2)
print(ar_1)
print()

ar_2=np.empty((5,7))
print(ar_2)
print()

ar_3=np.arange(1,10,2)
print(ar_3)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[1. 1.]

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

[1 3 5 7 9]


In [53]:
ar=np.eye(3)
print(ar)         

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
ar2=np.arange(2,10,2)
print(ar2)

[2 4 6 8]


In [67]:
ar_lin=np.linspace(2,12,num=6)   #initialization:2 end:12 elements:6
print(ar_lin)

[ 2.  4.  6.  8. 10. 12.]


In [159]:
var= np.random.rand(2,4)    #0 to 1 , only positive
print(var)
print()

var1=np.random.randn(3,4)   #0 to 1 , positive & negative
print(var1)
print()

var2=np.random.ranf(5)   #0.0 to 9.99999 
print(var2)
print()

x=np.array([1,2,3,4,5,67,8,8])
var3=np.random.shuffle(x) 
print(var3)

[[0.99901498 0.38527951 0.0582487  0.6114609 ]
 [0.6827166  0.86867374 0.88003433 0.00767403]]

[[-0.8681067   0.55809921 -0.12191717  0.35426807]
 [ 2.01049571  0.94331032 -2.16433741 -0.67304307]
 [-0.99362839  0.51160297 -1.70775956  0.0826947 ]]

[0.52907601 0.06140438 0.44412718 0.36624375 0.42922487]

None


In [51]:
r=np.random.randint(10,size=(8))   #under 10 ,8 values
print(r)
print()

r1=np.random.randint(150, size=(3, 5))    #under 150 , 3 rows & 5 columns
print(r1)
print()

r2=np.random.randint(2,10,4)   # min, max, number of values
print(r2)

[7 5 0 5 1 6 2 4]

[[120  14 144   2 144]
 [138  87 149  20  55]
 [ 18  93 140  81  18]]

[2 8 8 7]


In [45]:
x1=np.array([1,2,3,4])
print(x1)
print(x1.dtype)

[1 2 3 4]
int32


In [55]:
x1=np.array([1,2,3,4], dtype="f")
print(x1.dtype)

float32


In [65]:
y=np.array([1,2,3,4,5,6])
print(y)
print()

z=y.astype("m") 
print(z)
print()

z1=y.astype('c')
print(z1)


[1 2 3 4 5 6]

[1 2 3 4 5 6]

[b'1' b'2' b'3' b'4' b'5' b'6']


In [79]:
a=np.array([1,2,3])
b=np.array([[1],[2,],[3]])
print(a+b)
print()


a=([1,2,3,4])
b=([2,3,4,5])
add1=np.add(a,b)
print(add1)

[[2 3 4]
 [3 4 5]
 [4 5 6]]

[3 5 7 9]


In [89]:
x=np.array([1,2,3,4])
x1=np.sqrt(x)         #square root
print(x1)
print()

x2=np.sin(x)          #values of every sin0
print(x2)
print()

x3=np.cumsum(x)       #n1, n1+n2, n1+n2+n3, n1+n2+n3+n4
print(x3)

[1.         1.41421356 1.73205081 2.        ]

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]

[ 1  3  6 10]


In [73]:
var=np.array([1,2,3,4,5])
print(var.shape)    #rows*columns
print()

var=np.array([[1,2,3,4,5],[9,8,7,6,5]])
var1=var.shape
print(var1)

(5,)

(2, 5)


In [79]:
var1=np.array([1,2,3,4,5,6,1,2,2,3,2,3])
v=var1.reshape(3,2,2)   #logicallay
print(v)

[[[1 2]
  [3 4]]

 [[5 6]
  [1 2]]

 [[2 3]
  [2 3]]]


In [93]:
var=np.array([[1,2,3,4,5],[9,8,7,6,5]])
v=var.reshape(-1)                       #from any D to 1D
print(v)

[1 2 3 4 5 9 8 7 6 5]


In [101]:
#indexing
var1=np.array([1,2,3,4,5,6])
print(var1[3])
print()


x=np.array([[1,2,3],[2,4,6]])
print(x[1,2])      #1 for index of 2D array, 2 for 2D's arrays index(6)

4

6


In [121]:
#Slicing
var=np.array([1,2,3,4,5,6])
print(var[3:])
print()

print(var[1:5])    
print()

var2=np.array([[1,2,3,4,7],[4,5,6,8,10]])
print(var2[1,0:2])
print()

print(var2[0:1:])

[4 5 6]

[2 3 4 5]

[4 5]

[[1 2 3 4 7]]


In [127]:
x=np.array([2,4,6,8,10])
for i in x:
    print(i)

2
4
6
8
10


In [129]:
x=np.array([[[1,2,3,4],[9,7,6,5],[2,4,6,10]]])
for j in x:
    for k in j:
        for l in k:
            print(l)

1
2
3
4
9
7
6
5
2
4
6
10


In [131]:
x=np.array([[[1,2,3,4],[9,7,6,5],[2,4,6,10]]])

for i in np.nditer(x):       
    print(i)
    print()


for i,d in np.ndenumerate(x):      #with index
    print(i,d)

1

2

3

4

9

7

6

5

2

4

6

10

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 9
(0, 1, 1) 7
(0, 1, 2) 6
(0, 1, 3) 5
(0, 2, 0) 2
(0, 2, 1) 4
(0, 2, 2) 6
(0, 2, 3) 10


In [135]:
a=np.array([1,2,3,4])
b=np.array([9,7,8,6])

c= np.concatenate((a,b))    #row+row
print(c)
print()

d=np.stack((a,b))           #row & row
print(d)
print()

e=np.hstack((a,b))          #serial,row+row
print(e)
print()

f=np.dstack((a,b))          #rows are convert into columns
print(f)
print()

g=np.array_split(a,4)      #
print(g)

[1 2 3 4 9 7 8 6]

[[1 2 3 4]
 [9 7 8 6]]

[1 2 3 4 9 7 8 6]

[[[1 9]
  [2 7]
  [3 8]
  [4 6]]]

[array([1]), array([2]), array([3]), array([4])]


In [139]:
#Search
x=np.array([1,2,3,4,9,7,6,5,2,4,6,10])

a=np.searchsorted(x,[1,2,34,6])   #which index is perfect for these numbers
print(a)
print()

j=np.sort(x)            #serial
print(j)
print()

y=np.where(x==4)        #which index contains 4
print(y)


[ 0  1 12  4]

[ 1  2  2  3  4  4  5  6  6  7  9 10]

(array([3, 9], dtype=int64),)


In [143]:
#Filter
x=np.array([1,5,2,10])

f=[True, False, True, True]
v=x[f]
print(v)

[ 1  2 10]


In [151]:
var=np.array([1,5,2,10])

y=np.delete(var,3)   #index 3
print(y)
print()

d = np.insert(var,4,15)
print(d)

[1 5 2]

[ 1  5  2 10 15]


In [173]:
x=np.array([[1,2,3],[2,4,6]])

y=np.insert(x,[0,2],23, axis=1)
print(y)
print()

y1=np.insert(x,[0,2],23, axis=0)
print(y1)


[[23  1  2 23  3]
 [23  2  4 23  6]]

[[23 23 23]
 [ 1  2  3]
 [ 2  4  6]
 [23 23 23]]


In [169]:
x=np.array([[1,2,3],[2,4,6]])

p1=np.ravel(x)   #2D to 1D
print(p1)

[1 2 3 2 4 6]


In [163]:
x=np.array([1,2,3,4,5,67,8,8])
x1=np.unique(x,return_index=True)  
print(x1)

(array([ 1,  2,  3,  4,  5,  8, 67]), array([0, 1, 2, 3, 4, 6, 5], dtype=int64))


In [156]:
#Matrix

x=np.matrix([[1,2,3,4],[9,8,7,6]])
print(x)
print(type(x))

[[1 2 3 4]
 [9 8 7 6]]
<class 'numpy.matrix'>


In [175]:
x=np.matrix([[3,4],[7,6]])

y=np.linalg.inv(x)               #inverse matrix
print(y)
print()

z=np.linalg.matrix_power(x,2)    #power matrix
print(z)
print()

a=np.linalg.det(x)               #determine
print(a)


[[-0.6  0.4]
 [ 0.7 -0.3]]

[[37 36]
 [63 64]]

-10.000000000000002


In [187]:
x=np.matrix([[3,4],[7,6]])
x=np.transpose(x)
print(x)
print()

x1=(x.T)    #same as T

print(x1)
print()



[[3 7]
 [4 6]]

[[3 4]
 [7 6]]

